name: NuGet

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.300
        source-url: https://nuget.pkg.github.com/Bannerlord-Unofficial-Tools-Resources/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Pack Bannerlord.NexusmodsUploader (Release)
      run: dotnet pack Bannerlord.NexusmodsUploader/Bannerlord.NexusmodsUploader.csproj --configuration Release -o "./packages" 

    - name: Push with dotnet
      run: dotnet nuget push "./packages/*.nupkg"
