name: NuGet

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.300
        source-url: https://nuget.pkg.github.com/Aragas/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Pack Bannerlord.NexusmodsUploader (Release)
      run: dotnet pack Bannerlord.NexusmodsUploader/Bannerlord.NexusmodsUploader.csproj --configuration Release -o "./packages" 

    - name: Push (workaround)
      run: |
           for f in ./packages/*.nupkg
           do
             curl -vX PUT -u "vslee:${{secrets.GITHUB_TOKEN}}" -F package=@$f https://nuget.pkg.github.com/Aragas/
           done
      shell: bash
